name: request_sender
description: A package to sendRequest for package request_viewer
version: 1.0.5
homepage: https://github.com/modeckrus/request_viewer

environment:
  sdk: ">=2.18.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dio: ^4.0.6
  grpc: ^3.0.2
  protobuf: ^2.1.0
  request_model: 1.0.2
