name: request_model
description: A model for package request_sender
version: 1.0.1
homepage: https://github.com/modeckrus/request_viewer

environment:
  sdk: ">=2.16.1 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  equatable: ^2.0.5
  grpc: ^3.0.2
  protobuf: ^2.1.0
